### ISSUE TITLE
fix build problems

### ISSUE THREAD

**Issue by takawitter** [openlangrid/langrid#16]
There are so many errors when I import projects from Eclipse.
Please categorize those and fix problems by category.

For folder missing erros, create folder and create the file named .gitkeep in it and add/commit/push.
For errors for the projects whose name ends with .blank, leave those errors.
For other erros, please categorize and report here.

**Comment by trangmx** [comment]
I fixed errors, most of the errors is because of folder missing. 
I forgot to commit empty folders in my last commit.
Could you check again?

**Comment by takawitter** [comment]
Thanks for fixing errors.
But I still get many errors about JRE path.
I changed classpath of jp.go.nict.langrid.commons project.
Could you pull commit and check that this commit cause error in your environment?

**Comment by trangmx** [comment]
I pull the commit, it does not cause errors in my environment.

**Comment by takawitter** [comment]
Fine.
Then, please fix project classpaths.
For maven projects, just right-click one of projects, select Maven -> Update Project, Select All and OK.
For other projects, change settings as project uses workspace default.
